// Content script: swaps listing photos for Minecraft versions generated by the
// background worker. On-screen photos are generated first; other photos on the
// page (gallery, carousel slides) are pre-generated in the background so that
// opening the gallery or fullscreen view is instant. Every size variant of a
// photo shares one generated image (see canon.js).

(() => {
  const MIN_W = 180;
  const MIN_H = 120;
  const MIN_PREFETCH_W = 300; // skip agent headshots, logos, tiny thumbs
  const PENDING = "mc-pending";

  let enabled = true;
  let prefetchLimit = 30;
  const results = new Map(); // photo id -> { dataUrl, aspect }
  const failed = new Set(); // photo ids
  const requested = new Map(); // photo id -> "high" | "low"
  const lookedUp = new Set(); // photo ids already checked against the cache
  let prefetchPage = location.href;
  let prefetchCount = 0;

  const originalUrl = (img) => {
    const u = img.currentSrc || img.src;
    if (!u || u.startsWith("data:") || u.startsWith("blob:")) return null;
    if (/\.svg(\?|$)/i.test(u)) return null;
    return u;
  };

  // Intended display shape: from the URL when the CDN encodes it, else the
  // decoded image, else layout size.
  function dims(img, info) {
    if (info.dims) return info.dims;
    if (img.naturalWidth) return { w: img.naturalWidth, h: img.naturalHeight };
    const r = img.getBoundingClientRect();
    return { w: Math.round(r.width), h: Math.round(r.height) };
  }
  const aspect = ({ w, h }) => (w && h ? w / h : 0);

  const bigEnough = (img) => {
    const r = img.getBoundingClientRect();
    return r.width >= MIN_W && r.height >= MIN_H;
  };

  // At least half the image is inside the viewport and it's actually rendered.
  const inView = (img) => {
    const r = img.getBoundingClientRect();
    const visW = Math.min(r.right, innerWidth) - Math.max(r.left, 0);
    const visH = Math.min(r.bottom, innerHeight) - Math.max(r.top, 0);
    if (visW <= 0 || visH <= 0) return false;
    if (getComputedStyle(img).visibility === "hidden") return false;
    return visW * visH >= 0.5 * r.width * r.height;
  };

  function prefetchable(img, info) {
    if (prefetchLimit <= 0) return false;
    if (location.href !== prefetchPage) {
      prefetchPage = location.href;
      prefetchCount = 0;
    }
    return prefetchCount < prefetchLimit && dims(img, info).w >= MIN_PREFETCH_W;
  }

  function apply(img, url, dataUrl) {
    img.dataset.mcOriginal = url;
    // <picture><source srcset> would override img.src; neutralise them.
    const pic = img.parentElement?.tagName === "PICTURE" ? img.parentElement : null;
    pic?.querySelectorAll("source").forEach((s) => {
      if (s.dataset.mcSrcset === undefined) s.dataset.mcSrcset = s.srcset;
      s.srcset = dataUrl;
    });
    if (img.srcset) {
      img.dataset.mcSrcset = img.srcset;
      img.removeAttribute("srcset");
    }
    img.src = dataUrl;
    img.classList.remove(PENDING);
    img.classList.add("mc-done");
  }

  // Put a finished photo on every <img> showing any variant of it. Variants
  // with a different shape get a matching crop from the background cache.
  function applyEverywhere(id) {
    const res = results.get(id);
    for (const img of document.images) {
      const url = originalUrl(img);
      if (!url) continue;
      const info = photoInfo(url);
      if (info.id !== id) continue;
      const a = aspect(dims(img, info));
      if (!a || Math.abs(Math.log(a / res.aspect)) < 0.03) {
        apply(img, url, res.dataUrl);
      } else {
        chrome.runtime.sendMessage({ type: "lookup", url, ...dims(img, info) }, (r) => {
          if (r?.dataUrl && enabled && originalUrl(img) === url) apply(img, url, r.dataUrl);
        });
      }
    }
  }

  function store(id, dataUrl, d) {
    results.set(id, { dataUrl, aspect: aspect(d) || 1 });
    if (enabled) applyEverywhere(id);
  }

  function request(img, url, info, priority) {
    requested.set(info.id, priority);
    if (priority === "high") img.classList.add(PENDING);
    const d = dims(img, info);
    chrome.runtime.sendMessage({ type: "minecraftify", url, priority, ...d }, (res) => {
      requested.delete(info.id);
      for (const el of document.querySelectorAll(`img.${PENDING}`)) {
        const u = originalUrl(el);
        if (!u || photoInfo(u).id === info.id) el.classList.remove(PENDING);
      }
      if (res?.error === "cancelled") return void process(img); // retry if back on screen
      if (chrome.runtime.lastError || !res || res.error) {
        failed.add(info.id);
        if (res?.error) console.warn("[minecraftify]", res.error);
        return;
      }
      store(info.id, res.dataUrl, d);
    });
  }

  function process(img) {
    if (!enabled || !img.isConnected) return;
    const url = originalUrl(img);
    if (!url) return;
    const info = photoInfo(url);
    if (failed.has(info.id)) return;

    // Already generated (any variant): show it immediately, wherever it is.
    if (results.has(info.id)) return applyEverywhere(info.id);

    const pending = requested.get(info.id);
    if (bigEnough(img) && inView(img)) {
      if (pending === "high") img.classList.add(PENDING);
      else request(img, url, info, "high"); // also promotes a queued prefetch
      return;
    }
    if (pending || lookedUp.has(info.id)) return;

    // Off-screen: reuse a cached render for free, else queue it behind
    // on-screen work so it's ready when the gallery/fullscreen opens.
    lookedUp.add(info.id);
    const d = dims(img, info);
    chrome.runtime.sendMessage({ type: "lookup", url, ...d }, (res) => {
      if (res?.dataUrl) return store(info.id, res.dataUrl, d);
      if (enabled && !requested.has(info.id) && !results.has(info.id) && prefetchable(img, info)) {
        prefetchCount++;
        request(img, url, info, "low");
      }
    });
  }

  function leave(img) {
    const url = originalUrl(img);
    if (!url || !img.classList.contains(PENDING)) return;
    const id = photoInfo(url).id;
    img.classList.remove(PENDING);
    // Keep it high if another on-screen copy of the photo still wants it.
    for (const other of document.querySelectorAll(`img.${PENDING}`)) {
      const u = originalUrl(other);
      if (u && photoInfo(u).id === id) return;
    }
    if (requested.get(id) !== "high") return;
    requested.set(id, "low");
    chrome.runtime.sendMessage({ type: "leave", url });
  }

  const io = new IntersectionObserver(
    (entries) => {
      for (const e of entries) {
        if (e.isIntersecting) process(e.target);
        else leave(e.target);
      }
    },
    { threshold: 0.5 } // at least half on screen
  );

  const watch = (img) => {
    io.observe(img);
    process(img);
    if (!img.complete) img.addEventListener("load", () => process(img), { once: true });
  };

  function scan(root) {
    if (root.tagName === "IMG") watch(root);
    root.querySelectorAll?.("img").forEach(watch);
  }

  // Sites (React etc.) often swap src on existing nodes, so watch attributes too.
  const mo = new MutationObserver((muts) => {
    for (const m of muts) {
      if (m.type === "childList") m.addedNodes.forEach((n) => n.nodeType === 1 && scan(n));
      else if (m.target.tagName === "IMG" && !m.target.src.startsWith("data:")) {
        m.target.classList.remove("mc-done"); // site re-pointed it
        process(m.target);
      }
    }
  });

  function restoreAll() {
    document.querySelectorAll("img.mc-done").forEach((img) => {
      img.src = img.dataset.mcOriginal;
      if (img.dataset.mcSrcset) img.srcset = img.dataset.mcSrcset;
      img.classList.remove("mc-done");
    });
    document.querySelectorAll("source[data-mc-srcset]").forEach((s) => {
      s.srcset = s.dataset.mcSrcset;
      delete s.dataset.mcSrcset;
    });
    document.querySelectorAll(`img.${PENDING}`).forEach((img) => img.classList.remove(PENDING));
  }

  function start() {
    scan(document.body);
    mo.observe(document.body, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ["src", "srcset"],
    });
  }

  chrome.storage.local.get(["enabled", "prefetchLimit"], (s) => {
    enabled = s.enabled !== false;
    if (Number.isFinite(s.prefetchLimit)) prefetchLimit = s.prefetchLimit;
    start();
  });

  chrome.storage.onChanged.addListener((changes) => {
    if (changes.prefetchLimit) prefetchLimit = changes.prefetchLimit.newValue ?? 30;
    if (!changes.enabled) return;
    enabled = changes.enabled.newValue !== false;
    if (enabled) {
      failed.clear();
      lookedUp.clear();
      for (const img of document.images) process(img);
    } else {
      restoreAll();
    }
  });
})();
